sudo: required
services:
  - docker
before_install:
  #encrypt the setting to gcloud
  - openssl aes-256-cbc -K $encrypted_a126deee76a8_key -iv $encrypted_a126deee76a8_iv -in settings.json.enc -out settings.json -d
  # install the google cloud sdk to the travis ci
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  # make some configuration automatically
  - soucer $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  # link google sdk to my gmail account
  # video 231
  - gcloud auth activate-service-account --key-file service-account.json
  